jdbc.driver=${JDBC_DRIVER:net.sf.log4jdbc.sql.jdbcapi.DriverSpy}
jdbc.url=${JDBC_URL:jdbc:log4jdbc:mysql://localhost:3306/scoula_db}
jdbc.username=${JDBC_USERNAME:scoula}
jdbc.password=${JDBC_PASSWORD:1234}
