jdbc.driver=${JDBC_DRIVER:net.sf.log4jdbc.sql.jdbcapi.DriverSpy}
jdbc.url=${JDBC_URL:jdbc:log4jdbc:mysql://localhost:3306/kkobi?allowPublicKeyRetrieval=true&sslMode=DISABLED}
jdbc.username=${JDBC_USERNAME:kkobi}
jdbc.password=${JDBC_PASSWORD}